### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ruslo** [internaut/ogles_gpgpu#4]
Hi,

trying to open `http://www.mkonrad.net/projects/ogles_gpgpu.html` leads to redirection to incorrect address `https://mkonrad.netprojects/ogles_gpgpu.html`. I guess something wrong with site configs (?)

**Comment by internaut** [comment]
Thanks for reporting, that was a mistake in the HTTP to HTTPS redirection config on my server...

**Comment by ruslo** [comment]
Thanks, works fine now
